spring:
    datasource:
        url: jdbc:mysql://localhost:3306/furryfriend?serverTimeZone=Asia/Seoul
        username: root
        password: inhatc
        driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
        cache: false

    jpa:
        show-sql: true
        open-in-view: true