spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/furry
      username: root
      password: inhatc
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 526477563372-29m9nrid0oq8mk2rfvkb5rd8j9iquq0k.apps.googleusercontent.com
            client-secret: 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
            scope : profile, email
          naver:
            client-id: 0tWb0Sr4Ib9El2j8NGaG
            client-secret: q7lZ2fPVTq
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name, email, mobile
            client-name: Naver
          kakao:
            client-id: 8a03e9ddcf15f3e1a7a1da99b7963cf4
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

  profiles:
    include: oauth